apps/blog/urls.py
from django.urls import path

from . import views

app_name = 'article'

urlpatterns = [
        path('like/<int:post_id>', views.like_view, name='like'),    #google.com/blog/like/
        path('like_comment/<int:comment_id>', views.like_comment_view, name='like_comment'),    #google.com/blog/like_comment/

        path('dislike/<int:post_id>', views.dislike_view, name='dislike'),    #google.com/blog/dislike/
        path('dislike_comment/<int:comment_id>', views.dislike_comment_view, name='dislike_comment'),    #google.com/blog/dislike_comment/

        path('', views.index, name='index'),    #google.com/blog/
        path('post/<int:post_id>/', views.detail, name='detail'),    #google.com/blog/1/
        path('post/<int:post_id>/comment/', views.comment_view, name='comment'),    #google.com/blog/1/comment/
        
        path('create/', views.create_view, name='create'),    #google.com/blog/create/
        path('delete/<int:post_id>/', views.delete_view, name='delete'),    #google.com/blog/delete/1/
        path('update/<int:post_id>/', views.update_view, name='update'),    #google.com/blog/update/1/
    
    
]           

apps/members/urls.py
from django.urls import path

from . import views

app_name = 'members'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('profile/', views.profile_view, name='profile'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [ #google.com/
    path('admin/', admin.site.urls),#google.com/admin/
    path('article/', include('apps.blog.urls')),#google.com/blog/
    path('members/', include('apps.members.urls')),#google.com/members/
    path('', include('apps.main.urls')),#google.com/
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from PIL import Image
from django.core.files import File
from io import BytesIO

from django.db import models
from django.contrib.auth.models import User

from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill, Thumbnail, SmartCrop



# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts', null=True, blank=True, default=None)
        
    title = models.CharField(max_length=100)
    content = models.TextField()

    image = ProcessedImageField(
        upload_to='posts',
        processors=[ ResizeToFill(800, 400),
                    SmartCrop(800, 400)],
        format='JPEG',
        options={'quality': 60})
    thumbnail = ImageSpecField(
        source='image',
        processors=[Thumbnail(400, 200)],
        format='JPEG',
        options={'quality': 60})
    like = models.ManyToManyField(User, related_name='like_posts', blank=True)
    dislike = models.ManyToManyField(User, related_name='dislike_posts', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True) 


    class Meta:
        ordering = ['-created_at']
        
    
    
    def get_thumbnail(self):
        return self.thumbnail.url


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    # recursive comment reply system
    # parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='replies', null=True, blank=True)
    
    like = models.ManyToManyField(User, related_name='like_comments', blank=True)
    dislike = models.ManyToManyField(User, related_name='dislike_comments', blank=True)

    class Meta:
        ordering = ['-created_at']
        
    def __str__(self):
        return self.content

apps/blog/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'image')
        
        
class CommentForm(forms.Form):
    content = forms.CharField(min_length=6,max_length=200)

    

apps/blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, redirect
from django.http import JsonResponse, HttpResponse

from django.contrib import messages
from django.contrib.auth.decorators import login_required
#pagination
from django.core.paginator import Paginator

from .models import Post, Comment
from .forms import PostForm, CommentForm

# Create your views here.

def index(request):
    # print(request.GET.get('page', 1))   
    all_posts = Post.objects.all()
    paginator = Paginator(all_posts, 6)
    page = request.GET.get('page')
    all_posts_page = paginator.get_page(page)
    post_count = all_posts.count()
    
    context = {
        'post_count': post_count,
        'all_posts': all_posts_page,
        'created_form': PostForm()
    }
    return render(request, 'blog/index.html', context)


@login_required
def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    
    post = Post.objects.prefetch_related('comments').prefetch_related('comments__author').prefetch_related('comments__like').get(pk=post_id)
    update_form = PostForm(instance=post)
    context = {
        'post': post,
        'update_form': update_form
    }
    return render(request, 'blog/detail.html', context)

@login_required
def create_view(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(request, 'Post created successfully')
            return redirect('article:detail' , post_id=post.id)
        else:
            messages.error(request, 'Error creating post')
    return redirect('article:index')

@login_required
def delete_view(request, post_id):
    if request.method == 'POST':
        post = get_object_or_404(Post, pk=post_id, author=request.user)
        post.delete()
        messages.success(request, 'Post deleted successfully')
    return redirect('article:index')

@login_required
def update_view(request, post_id):
    if request.method == 'POST':
        post = get_object_or_404(Post, pk=post_id, author=request.user)
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, 'Post updated successfully')
        else:
            messages.error(request, 'Error updating post')
        return redirect('article:detail', post_id=post.id)
    return redirect('article:index')

@login_required
def like_view(request, post_id):
    if request.method == 'GET':
        post = get_object_or_404(Post, pk=post_id)
        if request.user in post.like.all():
            post.like.remove(request.user)
            user_like = False
        else:
            post.like.add(request.user)
            user_like = True
        return JsonResponse( {'like_count': post.like.count(), 'user_like': user_like} )


@login_required
def like_comment_view(request, comment_id):
    if request.method == 'GET':
        comment = get_object_or_404(Comment, pk=comment_id)
        if request.user in comment.like.all():
            comment.like.remove(request.user)
            user_like = False
        else:
            comment.like.add(request.user)
            user_like = True
        return JsonResponse( {'like_count': comment.like.count(), 'user_like': user_like} )
    
@login_required
def dislike_view(request, post_id):
    if request.method == 'GET':
        post = get_object_or_404(Post, pk=post_id)
        if request.user in post.dislike.all():
            post.dislike.remove(request.user)
            user_dislike = False
        else:
            post.dislike.add(request.user)
            user_dislike = True
        return JsonResponse( {'dislike_count': post.dislike.count(), 'user_dislike': user_dislike} )

@login_required
def dislike_comment_view(request, comment_id):
    if request.method == 'GET':
        comment = get_object_or_404(Comment, pk=comment_id)
        if request.user in comment.dislike.all():
            comment.dislike.remove(request.user)
            user_dislike = False
        else:
            comment.dislike.add(request.user)
            user_dislike = True
        return JsonResponse( {'dislike_count': comment.dislike.count(), 'user_dislike': user_dislike} )

@login_required
def comment_view(request, post_id):
    if request.method == 'POST':
        post = get_object_or_404(Post, pk=post_id)
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment.objects.create(
                post=post,
                author=request.user,
                content=form.cleaned_data['content']
            )
            messages.success(request, 'Comment created successfully')
        else:
            messages.error(request, 'Error creating comment')
    return redirect('article:detail', post_id=post_id)

apps/blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block title %}Blog{% endblock %}

{% block content %}
    <img src="{% if not post.image %}
    https://upload.wikimedia.org/wikipedia/ru/thumb/6/61/Rickrolling.gif/200px-Rickrolling.gif
    {% else %}
    {{ post.image.url }}
    
    {% endif %}" alt="Shoes" class="w-full max-h-96 object-cover mb-4" />

    <h1 class="text-3xl font-bold mb-4">{{ post.title }}</h1>
    {% if post.author == user %}
    <div class="my-4 border-b-2 border-gray-200 p-4">
        <a onclick="my_modal_4.showModal()" class="btn btn-secondary">Редагувати</a>
        <a onclick="delete_post.showModal()" class="btn btn-danger">Видалити</a>
    </div>
    {% endif %}
    <p class="text-gray-500 mb-4">Автор: {{ post.author }}</p>
    <p class="text-gray-500 mb-4">Дата: {{ post.created_at }}</p>
    <p class="mb-4">{{ post.content }}</p>
    <p class = "text-1xl font-bold mb-1">Кількість комментів: {{ post.comments.count }} </p>
    <!-- <a href="{% url 'article:index' %}" class="btn btn-primary">Назад</a> -->
    
    <hr class="my-4">
    <h3 class="text-2xl font-bold mb-4">Comments</h3>
    <form action="{% url 'article:comment' post_id=post.id %}" method="post">
        {% csrf_token %}
        <div class="grid grid-cols-1 gap-6">
            <div class="form-control">
                <textarea class="textarea textarea-bordered textarea-primary text-2xl" name="content" placeholder="Коментар" rows="3"></textarea>
            </div>
            <button class="btn btn-primary">Коментувати</button>
        </div>
    </form>
    <div class="grid grid-cols-1 gap-6 mt-4">
        {% for comment in post.comments.all %}
        <div class="p-4 bg-base-200 rounded-lg w-flex">
            <p class="text-gray-500 mb-4">Автор: {{ comment.author }}</p>
            <p class="text-gray-500 mb-4">Створений: {{ comment.created_at|timesince }} тому</p>
            <p>{{ comment.content }}</p>
            <button id="like_{{comment.id}}" onclick='like({{comment.id}})'  class="btn btn-square  text-white text-lg"><i class="fa-solid fa-thumbs-up {%if user in comment.like %}text-red-500{%else%}text-white{%endif%}"></i>{{ comment.like.count }}</button>
            <button id="dislike_{{comment.id}}" onclick='dislike({{comment.id}})'  class="btn btn-square  text-white text-lg"><i class="fa-solid fa-thumbs-down {%if user in comment.like %}text-black{%else%}text-white{%endif%}"></i>{{ comment.dislike.count }}</button>
        </div>
        {% endfor %}
    </div>



    <dialog id="my_modal_4" class="modal">
        <div class="modal-box w-11/12 max-w-5xl">
          <form method="dialog">
            <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
          </form>
          <h3 class="font-bold text-lg mb-4">Create Post</h3>
          <form action="{% url 'article:update' post.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="grid grid-cols-1 gap-6">
            {% for field in update_form %}
              <div class="form-control">
                  <label class="label">
                    <span class="label-text">{{ field.label }}</span>
                  </label>
               {% if field.name == 'content' %}
                <textarea class="textarea textarea-bordered" name="{{ field.name }}" placeholder="{{ field.label }}" rows="5">{{ field.value }}</textarea>
                {% elif field.name == 'image' %}
                <input type="file" name="{{ field.name }}" class="file-input file-input-bordered file-input-accent  w-full max-w-xs" placeholder="{{ field.label }}" value="{{ field.value }}">
                {% else %}
                <input type="{{ field.field.widget.input_type }}" name="{{ field.name }}" class="input input-bordered" placeholder="{{ field.label }}" value="{{ field.value }}">
                {% endif %}
              </div>
            {% endfor %}
            <button class="btn btn-primary">Create</button>
          </div>
            
          </form>
        </div>
      </dialog>


    <!-- MODAL FOR ACCEPT DELETE -->
    <dialog id="delete_post" class="modal">
        <div class="modal-box w-11/12 max-w-5xl">
          <form method="dialog">
            <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
          </form>
          <h3 class="font-bold text-lg mb-4">Delete Post</h3>
          <form action="{% url 'article:delete' post.id %}" method="post">
            {% csrf_token %}
            <div class="grid grid-cols-1 gap-6">
              <div class="form-control">
                  <label class="label">
                    <span class="label-text">Are you sure you want to delete this post?</span>
                    </label>
                </div>
                <button class="btn btn-danger">Delete</button>
                </div>
            </form>
        </div>
        </dialog>




        <script>
          function like(id) {
            fetch(`/article/like_comment/${id}`, {
              method: 'GET',
            })
              .then((res) => res.json())
              .then((data) => {
                if(data.user_like){
                document.getElementById(`like_${id}`).innerHTML = `<i class="fa fa-thumbs-up text-red-500"></i> ${data.like_count}`;
                }else{
                  document.getElementById(`like_${id}`).innerHTML = `<i class="fa fa-thumbs-up text-white"></i> ${data.like_count}`;
                }
              })
              .catch((error) => {
                console.error('Error:', error);
                  // Redirect to the login page
                //window.location.href = "{% url 'members:login' %}";
              })}
            </script>

          <script>
          function dislike(id) {
            fetch(`/article/dislike_comment/${id}`, {
              method: 'GET',
            })
              .then((res) => res.json())
              .then((data) => {
                if(data.user_like){
                document.getElementById(`dislike_${id}`).innerHTML = `<i class="fa fa-thumbs-down text-black"></i> ${data.dislike_count}`;
                }else{
                  document.getElementById(`dislike_${id}`).innerHTML = `<i class="fa fa-thumbs-down text-white"></i> ${data.dislike_count}`;
                }
              })
              .catch((error) => {
                console.error('Error:', error);
                  // Redirect to the login page
                //window.location.href = "{% url 'members:login' %}";
              });
          }
        </script>
{% endblock %}
  

apps/blog/templates/blog/index.html
{% extends 'base.html' %}
{% block title %}Blog{% endblock %}

{% block content %}
    <div class="my-4 rounded-lg bg-base-300 p-9 ">
    <h1 class = "text-3xl font-bold mb-4">Blog</h1>
    <h1 class = "text-1xl font-bold mb-5">Кількість: {{ post_count }} </h1>
    <a onclick="my_modal_4.showModal()" class="btn btn-accent">Create Post</a>
    <div class="my-4 border-b-2 border-gray-300 w-full"></div>
    <div class="grid grid-cols-3 gap-7">
        {% for post in all_posts %}
    
          {% include 'blog/_include_blocks/_card_post.html' with post=post %}

        {% endfor %}
    </div>
    <div class="join align-center justify-center flex my-4">
      {% if all_posts.has_previous %}
      <a href="?page=1" class="join-item btn">«</a>
      <a href="?page={{ all_posts.previous_page_number }}" class="join-item btn">Page {{ all_posts.previous_page_number }}</a>
      {% endif %}

      <button class="join-item btn btn-primary">Page {{ all_posts.number }}</button>

      {% if all_posts.has_next %}
      <a href="?page={{ all_posts.next_page_number }}" class="join-item btn">Page {{ all_posts.next_page_number }}</a>
      <a href="?page={{ all_posts.paginator.num_pages }}" class="join-item btn">»</a>
      
      {% endif %}
    </div>
  </div>




  <dialog id="my_modal_4" class="modal">
    <div class="modal-box w-11/12 max-w-5xl">
      <form method="dialog">
        <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
      </form>
      <h3 class="font-bold text-lg mb-4">Create Post</h3>
      <form action="{% url 'article:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="grid grid-cols-1 gap-6">
        {% for field in created_form %}
          <div class="form-control">
              <label class="label">
                <span class="label-text">{{ field.label }}</span>
              </label>
           {% if field.name == 'content' %}
            <textarea class="textarea textarea-bordered" name="{{ field.name }}" placeholder="{{ field.label }}" rows="5"></textarea>
            {% elif field.name == 'image' %}
            <input type="file" name="{{ field.name }}" class="file-input file-input-bordered file-input-accent  w-full max-w-xs" placeholder="{{ field.label }}">
            {% else %}
            <input type="{{ field.field.widget.input_type }}" name="{{ field.name }}" class="input input-bordered" placeholder="{{ field.label }}">
            {% endif %}
          </div>
        {% endfor %}
        <button class="btn btn-primary">Create</button>
      </div>
        
      </form>
    </div>
  </dialog>



<script>
  function like(id) {
    fetch(`like/${id}`, {
      method: 'GET',
    })
      .then((res) => res.json())
      .then((data) => {
        if(data.user_like){
        document.getElementById(`like_${id}`).innerHTML = `<i class="fa fa-thumbs-up text-red-500"></i> ${data.like_count}`;
        }else{
          document.getElementById(`like_${id}`).innerHTML = `<i class="fa fa-thumbs-up text-white"></i> ${data.like_count}`;
        }
      })
      .catch((error) => {
        console.error('Error:', error);
          // Redirect to the login page
        window.location.href = "{% url 'members:login' %}";
      })}
      </script>

<script>
  function dislike(id) {
    fetch(`dislike/${id}`, {
      method: 'GET',
    })
      .then((res) => res.json())
      .then((data) => {
        if(data.user_dislike){
        document.getElementById(`dislike_${id}`).innerHTML = `<i class="fa fa-thumbs-down text-black"></i> ${data.dislike_count}`;
        }else{
          document.getElementById(`dislike_${id}`).innerHTML = `<i class="fa fa-thumbs-down text-white"></i> ${data.dislike_count}`;
        }
      })
      .catch((error) => {
        console.error('Error:', error);
          // Redirect to the login page
        window.location.href = "{% url 'members:login' %}";
      });
      
    }
  </script>
{% endblock %}
  