apps/blog/urls.py
from django.urls import path

from . import views

app_name = 'article'

urlpatterns = [
        path('like/<int:post_id>', views.like_view, name='like'),    #google.com/blog/like/
        path('like_comment/<int:comment_id>', views.like_comment_view, name='like_comment'),    #google.com/blog/like_comment/

        path('dislike/<int:post_id>', views.dislike_view, name='dislike'),    #google.com/blog/dislike/
        path('dislike_comment/<int:comment_id>', views.dislike_comment_view, name='dislike_comment'),    #google.com/blog/dislike_comment/

        path('', views.index, name='index'),    #google.com/blog/
        path('post/<int:post_id>/', views.detail, name='detail'),    #google.com/blog/1/
        path('post/<int:post_id>/comment/', views.comment_view, name='comment'),    #google.com/blog/1/comment/
        
        path('create/', views.create_view, name='create'),    #google.com/blog/create/
        path('delete/<int:post_id>/', views.delete_view, name='delete'),    #google.com/blog/delete/1/
        path('update/<int:post_id>/', views.update_view, name='update'),    #google.com/blog/update/1/
    
    
]           

apps/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('lol/', views.lol, name='lol'),
    
]

apps/members/urls.py
from django.urls import path

from . import views

app_name = 'members'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('profile/', views.profile_view, name='profile'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [ #google.com/
    path('admin/', admin.site.urls),#google.com/admin/
    path('article/', include('apps.blog.urls')),#google.com/blog/
    path('members/', include('apps.members.urls')),#google.com/members/
    path('', include('apps.main.urls')),#google.com/
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/_include_blocks/_nav_block.html
<div class="navbar bg-base-300">
    <div class="container mx-auto">
    <div class="navbar-start">
      <a class="btn btn-ghost text-xl" href="{% url 'main:index' %}">
        <svg width="30" height="30" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMinYMin meet">
            <path d="M245.235 153.524c14.012-14.012 14.011-36.811 0-50.823-6.787-6.788-15.812-10.525-25.411-10.525-2.28 0-4.523.208-6.712.617 9.538-6.524 15.72-17.495 15.72-29.694 0-19.816-16.122-35.937-35.938-35.937-12.223 0-23.213 6.205-29.733 15.776 2.157-11.377-1.226-23.537-9.87-32.18C146.506 3.97 137.48.232 127.882.232c-9.6 0-18.624 3.738-25.412 10.526-8.643 8.643-12.026 20.803-9.87 32.18-6.519-9.57-17.509-15.776-29.733-15.776-19.815 0-35.936 16.12-35.936 35.937 0 12.2 6.18 23.17 15.718 29.694a36.487 36.487 0 0 0-6.711-.617c-9.6 0-18.624 3.738-25.411 10.526C3.738 109.489 0 118.514 0 128.112c0 9.6 3.738 18.624 10.526 25.412 6.787 6.787 15.812 10.526 25.41 10.526 2.28 0 4.523-.208 6.712-.618-9.538 6.525-15.718 17.496-15.718 29.695 0 19.815 16.12 35.936 35.936 35.936 12.224 0 23.215-6.206 29.734-15.776-2.157 11.378 1.226 23.538 9.87 32.18 6.787 6.788 15.812 10.526 25.41 10.526 9.6 0 18.625-3.738 25.412-10.526 8.643-8.643 12.026-20.803 9.869-32.18 6.52 9.57 17.51 15.776 29.733 15.776 19.816 0 35.937-16.12 35.937-35.936 0-12.2-6.18-23.17-15.719-29.695 2.189.41 4.433.618 6.712.618 9.599 0 18.624-3.739 25.411-10.526"/>
            <path d="M234.391 113.538c-8.049-8.048-21.099-8.048-29.148 0h-42.184l29.829-29.828c11.383 0 20.61-9.228 20.61-20.611 0-11.383-9.227-20.612-20.61-20.612-11.384 0-20.611 9.229-20.611 20.612l-29.829 29.829V50.743c8.049-8.049 8.049-21.099 0-29.148-8.05-8.05-21.1-8.05-29.149 0s-8.049 21.1 0 29.148v42.185l-29.828-29.83c0-11.382-9.228-20.61-20.611-20.61-11.383 0-20.611 9.228-20.611 20.61 0 11.384 9.228 20.612 20.61 20.612l29.83 29.828H50.504c-8.05-8.049-21.1-8.048-29.15 0-8.048 8.05-8.048 21.1 0 29.15 8.05 8.048 21.1 8.048 29.15 0h42.183L62.86 172.515c-11.383 0-20.611 9.227-20.611 20.61 0 11.384 9.228 20.612 20.61 20.612 11.384 0 20.612-9.228 20.612-20.611l29.828-29.829v42.184c-8.049 8.049-8.049 21.1 0 29.149 8.05 8.049 21.1 8.049 29.15 0 8.048-8.05 8.048-21.1 0-29.15v-42.183l29.828 29.829c0 11.383 9.227 20.61 20.61 20.61 11.384 0 20.612-9.227 20.612-20.61 0-11.384-9.228-20.611-20.611-20.611l-29.83-29.829h42.185c8.05 8.05 21.1 8.05 29.148 0 8.05-8.049 8.05-21.1 0-29.149" fill="#FFB13B"/>
        </svg>
        My First Site
    </a>
    </div>
    <div class="navbar-center flex">
      <ul class="menu menu-horizontal px-1">
        <li><a href="{% url 'main:lol' %}">lol</a></li>
        <li><a href="{% url 'article:index' %}">Blog</a></li>
      </ul>
    </div>
    <div class="navbar-end flex">
      

      {% if user.is_authenticated %}
      <div class="dropdown dropdown-end">
        <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
          <div class="w-10 rounded-full">
            <img alt="Tailwind CSS Navbar component" src="https://daisyui.com/images/stock/photo-1534528741775-53994a69daeb.jpg" />
          </div>
        </div>
        <ul tabindex="0" class="mt-3 z-[1] p-2 shadow menu menu-sm dropdown-content bg-base-200 rounded-box w-52">
          <span class="p-2 text-sm text-primary">Hello, <b>{{ user.username }}</b></span>
          <hr class="my-2 border-base-100">
          <li>
            <a class="justify-between" href="{% url 'members:profile' %}">
              Profile
              <span class="badge">New</span>
            </a>
          </li>
          <li><a href="{% url 'members:logout' %}">Logout</a></li>
        </ul>
      </div>
      {% else %}
        <a href="{% url 'members:login' %}" class="btn btn-ghost">Login</a>
        <a href="{% url 'members:signup' %}" class="btn btn-ghost">Signup</a>
      {% endif %}
    </div>
    </div>
  </div>